# Generated by Django 4.1 on 2022-08-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clubuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="User Email"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=300)),
                ("zipcode", models.CharField(max_length=15, verbose_name="zip code")),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Phone contact"),
                ),
                ("web", models.URLField(verbose_name="Website Address")),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, null=True, to="event.clubuser"),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event.venue",
            ),
        ),
    ]
