# Generated by Django 4.1 on 2022-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_event_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(default=1, verbose_name="Venue Owner"),
        ),
    ]
