# Generated by Django 4.1 on 2022-10-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_venue_venue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
